### PR TITLE
Compliance check changes to handle exceptions

### PR DESCRIPTION
**Pull request by balavigneshVMware**

### CODE REVIEW

**Comment by murugesan-raja** [comment]
LGTM

**Comment by dmurphy18** [comment]
@balavigneshVMware Recommend doing the following in your git branch 

- pre-commit install

This will install pre-commit hooks into .git/hooks which should ensure that no commit is successful until pre-commit has been successful.

Also there is are no tests excising your changes, presuming that current tests are insufficient to test your changes.

**Comment by murugesan-raja** [comment]
Tests can't be run in pipeline as we don't have config module uploaded to PyPi repo yet. Here are the tests run in local.

image

image

**Comment by dmurphy18** [comment]
Here are examples for pulling in from GitHub that which would be finally loaded from PyPI

`
## bcrypt
git+https://github.com/dmurphy18/bcrypt@fix_cffi_junos_bld#egg=bcrypt

## PyNaCl
git+https://github.com/dmurphy18/pynacl@fix_cffi_junos_bld#egg=pynacl

## cryptography==3.1.1
git+https://github.com/dmurphy18/cryptography@sign-conversion-2.6.1#egg=cryptography
`

We had discussed how to do this, you should so you can adequately test your code.

**Pull request merged**
