### PR TITLE
Added integration tests for vmc_vm_stats module

### PR DESCRIPTION
**Pull request by shaikres**
Added integration tests for vmc_vm_stats module.
updated readme for vmc docs to include information on how to get ``vm_id``

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
These tests are failing when I run them locally

**Comment by waynew** [comment]
Currently this is probably ready to merge, but until the upstream issue is fixed in our test environment I don't want to merge this because then all of the test runs will end out failing.

**Comment by shaikres** [comment]
> Currently this is probably ready to merge, but until the upstream issue is fixed in our test environment I don't want to merge this because then all of the test runs will end out failing.

hi @waynew , the upstream issue with vmc is resolved now and we deployed new SDDC. we will share the required details over slack. Please run these tests once in your environment and merge this PR

**Comment by waynew** [comment]
An unrelated test failed due to timeout but re-running that one in isolation was fine. Re-running the tests, but this is probably ready to merge

**Comment by waynew** [comment]
okay so an entirely different test failed with a gateway timeout:

```
E       AssertionError: assert 'error' not in {'error': '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</cen
ter>\r\n</body>\r\n</html>\r\n'}
```

I'm going to go out on a limb and say that I think these are just random Internet issues and not actually related to the tests being flaky. We can go ahead and merge this, but if our normal test suites start failing then we'll need to come back and start looking at this.

**Review by waynew — APPROVED** [review]

**Pull request merged**
