### PR TITLE
Adjust dependencies to allow installation on Salt OneDir

### LINKED ISSUE #317: Can't install saltext.vmware on Salt OneDir 3005.1
pip can't solve dependencies for this extension on Salt 3005.1 (OneDir), jinja is pinned to jinja2==3.1.0 but this extension has a dependency for jinja<=3.0.1. Below is on AlmaLinux release 8.6 (Sky Tiger)

```
# salt-pip install saltext.vmware
Collecting saltext.vmware
  Downloading saltext.vmware-22.9.8.0rc1-py2.py3-none-any.whl (350 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 350.6/350.6 kB 38.3 MB/s eta 0:00:00
Requirement already satisfied: salt>=3002 in /opt/saltstack/salt/run (from saltext.vmware) (3005.1)
Collecting jinja2<=3.0.1
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 13.5 MB/s eta 0:00:00
Collecting pyvmomi==7.0.2
  Downloading pyvmomi-7.0.2.tar.gz (589 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.6/589.6 kB 41.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests>=2.3.0 in /opt/saltstack/salt/run (from pyvmomi==7.0.2->saltext.vmware) (2.25.1)
Requirement already satisfied: six>=1.7.3 in /opt/saltstack/salt/run (from pyvmomi==7.0.2->saltext.vmware) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/saltstack/salt/run (from jinja2<=3.0.1->saltext.vmware) (2.0.1)
Requirement already satisfied: pytz==2022.1 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (2022.1)
Requirement already satisfied: jaraco.classes==3.2.1 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (3.2.1)
Requirement already satisfied: more-itertools==5.0.0 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (5.0.0)
Requirement already satisfied: jaraco.functools==2.0 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (2.0)
Requirement already satisfied: python-gnupg==0.4.8 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (0.4.8)
Requirement already satisfied: jaraco.text==3.5.1 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (3.5.1)
Requirement already satisfied: cffi==1.14.6 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (1.14.6)
Requirement already satisfied: importlib-metadata==4.6.4 in /opt/saltstack/salt/run (from salt>=3002->saltext.vmware) (4.6.4)
Collecting salt>=3002
  Downloading salt-3005.tar.gz (17.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 31.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/c1/8b/f21efb024adbb6929cba84040882bf9fd6427fd786dd0596e7e23a9cf717/salt-3005.tar.gz (from https://pypi.org/simple/salt/) (requires-python:>=3.5)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/c1/8b/f21efb024adbb6929cba84040882bf9fd6427fd786dd0596e7e23a9cf717/salt-3005.tar.gz (from saltext.vmware) has inconsistent version: filename has '3005', but metadata has '3005.1'[reset]
  Downloading salt-3004.2.tar.gz (17.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 41.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/78/47/0acfc5d43fcf4b01c3f650ce884525dd2330b8827364e4509819f7e925d3/salt-3004.2.tar.gz (from https://pypi.org/simple/salt/) (requires-python:>=3.5)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/78/47/0acfc5d43fcf4b01c3f650ce884525dd2330b8827364e4509819f7e925d3/salt-3004.2.tar.gz (from saltext.vmware) has inconsistent version: filename has '3004.2', but metadata has '3005.1'[reset]
  Downloading salt-3004.1.tar.gz (17.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 33.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/2f/31/73c98765b59608fe6742824af31f2037ef1490e46a95873a07a34b596f15/salt-3004.1.tar.gz (from https://pypi.org/simple/salt/) (requires-python:>=3.5)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/2f/31/73c98765b59608fe6742824af31f2037ef1490e46a95873a07a34b596f15/salt-3004.1.tar.gz (from saltext.vmware) has inconsistent version: filename has '3004.1', but metadata has '3005.1'[reset]
  Downloading salt-3004.tar.gz (17.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 51.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/0f/35/e4e1f092eb1a22e807f9bcc5712701bf4d55f9ab41eb2cca55680817ef05/salt-3004.tar.gz (from https://pypi.org/simple/salt/) (requires-python:>=3.5)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/0f/35/e4e1f092eb1a22e807f9bcc5712701bf4d55f9ab41eb2cca55680817ef05/salt-3004.tar.gz (from saltext.vmware) has inconsistent version: filename has '3004', but metadata has '3005.1'[reset]
  Downloading salt-3003.5.tar.gz (16.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 47.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/c8/d1/fbc668e5c5018c33910932ac7c8047384055faeef49a38cc8044b2137309/salt-3003.5.tar.gz (from https://pypi.org/simple/salt/)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/c8/d1/fbc668e5c5018c33910932ac7c8047384055faeef49a38cc8044b2137309/salt-3003.5.tar.gz (from saltext.vmware) has inconsistent version: filename has '3003.5', but metadata has '3005.1'[reset]
  Downloading salt-3003.4.tar.gz (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 39.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/77/6b/5404f0fcc0c772de81443e96accaf5a0fd1652e2e5482ee2fbfb6482537f/salt-3003.4.tar.gz (from https://pypi.org/simple/salt/)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/77/6b/5404f0fcc0c772de81443e96accaf5a0fd1652e2e5482ee2fbfb6482537f/salt-3003.4.tar.gz (from saltext.vmware) has inconsistent version: filename has '3003.4', but metadata has '3005.1'[reset]
  Downloading salt-3003.3.tar.gz (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 41.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/71/8a/02f957ad4ebfe28002ceef891c8fa0780c4bd75d4882af8c0228dbd2084d/salt-3003.3.tar.gz (from https://pypi.org/simple/salt/)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/71/8a/02f957ad4ebfe28002ceef891c8fa0780c4bd75d4882af8c0228dbd2084d/salt-3003.3.tar.gz (from saltext.vmware) has inconsistent version: filename has '3003.3', but metadata has '3005.1'[reset]
  Downloading salt-3003.2.tar.gz (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 52.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/e3/cf/b423b3928f5b2fdc9fd4e330e9f765f15fb6b90d60513d6f4b1649c409eb/salt-3003.2.tar.gz (from https://pypi.org/simple/salt/)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/e3/cf/b423b3928f5b2fdc9fd4e330e9f765f15fb6b90d60513d6f4b1649c409eb/salt-3003.2.tar.gz (from saltext.vmware) has inconsistent version: filename has '3003.2', but metadata has '3005.1'[reset]
  Downloading salt-3003.1.tar.gz (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 51.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding [blue underline]https://files.pythonhosted.org/packages/49/51/5c6dd25abeda4e11fc8bfbc80601bec5b14e9534c7a031d13bfb90e41fd3/salt-3003.1.tar.gz (from https://pypi.org/simple/salt/)[/]: [yellow]Requested salt>=3002 from https://files.pythonhosted.org/packages/49/51/5c6dd25abeda4e11fc8bfbc80601bec5b14e9534c7a031d13bfb90e41fd3/salt-3003.1.tar.gz (from saltext.vmware) has inconsistent version: filename has '3003.1', but metadata has '3005.1'[reset]
  Downloading salt-3003.tar.gz (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 44.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-95nzygz3
```

### PR DESCRIPTION
**Pull request by ggiesen**
This is a naive fix to adjust dependencies to match Salt OneDir 3005.1. I haven't been able to test this yet as I'm still trying to get `vsphere-automation-sdk-python` to install as well.

Also bumps pyVmomi to 7.0.3

Fixes #317

### CODE REVIEW

**Comment by ggiesen** [comment]
Looks like tests are failing due to the bumped jinja2 which has deprecated using `jinja2.Markup()` syntax in favour of `markupsafe.Markup()` per https://github.com/pallets/jinja/issues/1438

**Comment by waynew** [comment]
@ggiesen Seems reasonable to me - I'm pretty sure it's because our dep on salt is set to 3004>= - I don't remember which version got that markup thing busted. I'm :+1: on changing the test deps for sure to require 3005(.1?)

**Comment by ggiesen** [comment]
re-run all

**Comment by waynew** [comment]
Hrm. I think there's an upstream issue with that req file being missing in 3005.1 for 3.7 on mac? :thinking:

**Comment by waynew** [comment]
@ggiesen do you mind rebasing this on the latest main? I *think* that should let us get this merged in...

**Comment by ggiesen** [comment]
@waynew I moved the MacOS 3.9 tests to 3.9. I'm not sure if that's the right approach but I assume since Salt master branch only has 3.9 that it's no longer supported on 3.7 on MacOS (I'm not a Mac guy so I don't know what the Python ecosystem looks like on Mac). It's passing now except for one of the Linux tests that failed because of connectivity issues and I have no way to restart the tests.

**Comment by waynew** [comment]
@ggiesen that seems reasonable. I think as long as it runs on some version on mac we're good :+1: (we're basically pure Python in this module anyway so we're kinda holding Salt invariant with the tests here - but Salt has to be installed and I'm pretty sure that's what was failing)

**Review by waynew — APPROVED** [review]
Cool, looks like we're passing now. I haven't seen any objections so I'm going to go ahead and merge this :+1:

**Pull request merged**
