### PR TITLE
Get configuration and get desired configuration using config modules

### PR DESCRIPTION
**Pull request by jgangel**
Call get desired configuration ready

Implement get configuration and get desired configuration execution modules

Fix on get configuration and get desired configuration return

Add get configuration and get desired configuration documentation

### CODE REVIEW

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Wondering about pytests for the changes, or do existing tests already cover the changes made, and if so, what tests are those ?

**Comment by dmurphy18** [comment]
Just noticed from examining the tests run, that there is no Python 3.10 testing.  This needs to get added, will investigate getting this added to the repo

**Comment by jgangel** [comment]
Yes @dmurphy18, is there a way to mark this PR as draft? I am currently working on the pytest for these changes done. Also, this is not expected to be merged into main, only to our unified-config branch.

**Comment by dmurphy18** [comment]
@jgangel I see you found 'draft', also on the Salt Team we prepend [WIP] for Work In Progress to let others know it is not finished yet, for example:
```
[WIP] Get configuration and get desired configuration using config modules
```
As for unified-config branch, it is expected that some day it will be merged into the main branch, or else it should be in its own repository.  Also need to test on Python 3.10 since that is what Salt 3006.x uses and you want to make sure there are no hidden gottas.

**Review by jgangel — COMMENTED** [review]
Added unit tests for both execution modules

**Review by dmurphy18 — APPROVED** [review]

**Pull request merged**
